# -*- mode: python; -*- 
# 
# 

import frogsutils

def build( bld ):
    
    sources = bld.path.ant_glob('*.cc', 
                                excl=['lightcurveguru.cc', 
                                      'psfphot.cc', 
                                      'daopsfphot.cc', 
                                      'daopsffitphot.cc'])
    
    #    sources.remove('lightcurveguru.cc')
    #    sources.remove('psfphot.cc')
    #    sources.remove('daopsfphot.cc')
    #    sources.remove('daopsffitphot.cc')
    
    lib = bld.shlib(
        source   = sources,
        target   = 'toadslc', 
        includes = [ '.', 
                     '../src_base', 
                     '../src_utils', 
                     '../src',
                     '../psf' ], 
        lib      = [ 'm' ], 
        use      = [ 'toads_base', 
                     'toads_utils', 
                     'toadspsf', 
                     'toadslib' ],
        vnum     = frogsutils.get_version_number())
    lib.rpath = [bld.env.PREFIX + '/lib']
    lib.rpath += bld.env.LIBPATH_CFITSIO
    lib.rpath += bld.env.LIBPATH_SEX
    
    
#     bld( features = "cxx cprogram", 
#          source   = "make_lightcurve.cc", 
#          includes = [ '.' ],
#          uselib_local = [ 'toads_base', 
#                           'toads_utils', 
#                           'toadspsf', 
#                           'toadslib', 
#                           'toadslc' ],
#          vnum  = '0.1.0' )
         
