# -*- mode: python -*-
# 



import frogsutils

def build( bld ):
    
    sources = bld.path.ant_glob('*.cc')
    
    lib = bld.shlib(# features = 'cxx cshlib', 
        source = sources,
        target = 'toadspsf', 
        includes = [ '.', '../src_utils', '../src_base', '../src' ], 
        libs     = [ 'm' ], 
        use = [ 'toadslib', 'toads_base', 'toads_utils' ],
        vnum     = frogsutils.get_version_number())
    
    lib.rpath = [bld.env.PREFIX + '/lib']
    lib.rpath += bld.env.LIBPATH_CFITSIO
    lib.rpath += bld.env.LIBPATH_SEX

    # install the headers 

    bld.install_files('${PREFIX}/${PKG_INCDIR}', [ 'analyticpsf.h', 'psfstar.h', 'imagepsf.h'])
#    for tg in ['testder'] :
#        prog = bld.program(
#            source   = tg+".cc",
#            target   = tg,
#            includes = [ '.', '../src_utils', '../src_base', '../src' ], 
#            use = [ 'toadspsf'] )
#        prog.rpath = [bld.env['PREFIX'] + '/lib']
#        prog.rpath += bld.env.LIBPATH_CFITSIO
#        prog.rpath += bld.env.LIBPATH_SEX
