#!/usr/bin/env python


Import('g_env')

EXTRA_DIST = [
    'SConscript',
    'cernlib.m4',  'cmt.m4',
    'imagemagick.m4',
    'poloka.m4',   'swig.m4',
    'cfitsio.m4',  'libxml.m4',
    'sex.m4'
]

g_env.AddToDist(EXTRA_DIST)

