#!/usr/bin/env python

import os
#from config import Glob

Import('g_env')
local_env = g_env.Copy()

EXTRA_DIST     = ['kernnum/pilot.h',
                  'Makefile.am', 'SConscript']

SOURCE_FILES   = [
    'dfact.F',    'dfeqn.F',    'dfinv.F',
    'dsinv.F',    'eisrs1.F',   'tmprnt.F',
    'tql2.F',     'tred2.F'
    ]

NOINST_HEADER_FILES = [
    'fact.inc',    'feqn.inc',    'finv.inc',
    'sfactd.inc',  'sfact.inc',   'sfinv.inc'
    ]

#local_env.AddExternalDep(None,
#                         ['/usr/local/cern/pro/lib'],
#                         ['packlib', 'nsl', 'crypt', 'dl', 'g2c'])
local_env.ActivateExternalPackage('cern')

shlib = local_env.SharedLibrary(target='cern_stuff', source=SOURCE_FILES)

local_env.InstallLibs([shlib])
g_env.AddToDist(EXTRA_DIST + SOURCE_FILES + NOINST_HEADER_FILES)


