# -*- mode: python -*-
# 

import frogsutils

def build( bld ):
    
    sources = bld.path.ant_glob('*.F')
        
    lib = bld(features = 'fc fcshlib', 
              source = sources,
              target = 'cern_stuff', 
              vnum     = frogsutils.get_version_number())

    
