.TH "basestar.h" 3 "8 Feb 2004" "toads" \" -*- nroff -*-
.ad l
.nh
.SH NAME
basestar.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fR
.br
\fC#include <cstdio>\fR
.br
\fC#include <string>\fR
.br
\fC#include "point.h"\fR
.br
\fC#include "countedref.h"\fR
.br
\fC#include "rootstuff.h"\fR
.br
\fC#include "starlist.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBBaseStar\fR"
.br
.RI "\fIThe base class for handling stars. Used by all matching routines.\fR"
.in -1c
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBMEMPIX2DISK\fR  1"
.br
.ti -1c
.RI "#define \fBDECALAGE_IJ_XY\fR  0."
.br
.ti -1c
.RI "#define \fBDECALAGE_XY_IJ\fR  0."
.br
.in -1c
.SS Typedefs

.in +1c
.ti -1c
.RI "typedef \fBStarList\fR<\fBBaseStar\fR> \fBBaseStarList\fR"
.br
.ti -1c
.RI "typedef BaseStarList::const_iterator \fBBaseStarCIterator\fR"
.br
.ti -1c
.RI "typedef BaseStarList::iterator \fBBaseStarIterator\fR"
.br
.ti -1c
.RI "typedef \fBCountedRef\fR<\fBBaseStar\fR> \fBBaseStarRef\fR"
.br
.in -1c
.SS Functions

.in +1c
.ti -1c
.RI "bool \fBDecreasingFlux\fR (const \fBBaseStar\fR *S1, const \fBBaseStar\fR *S2)"
.br
.RI "\fIenables to sort easily a starList (of anything that derives from \fBBaseStar\fR).\fR"
.ti -1c
.RI "int \fBDecodeFormat\fR (const char *FormatLine, const char *StarName)"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for toads from the source code.