.TH "fastfinder.h" 3 "8 Feb 2004" "toads" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fastfinder.h \- Fast locator in starlists. 
.SH SYNOPSIS
.br
.PP
\fC#include "basestar.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBFastFinder\fR"
.br
.RI "\fIFast locator in starlists.\fR"
.ti -1c
.RI "class \fBFastFinder::Iterator\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Fast locator in starlists.
.PP
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for toads from the source code.