.TH "FitsSlice" 3 "8 Feb 2004" "toads" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FitsSlice \- Memory saving traversal of a fits image. 
.SH SYNOPSIS
.br
.PP
\fC#include <fitsslice.h>\fR
.PP
Inherits \fBFitsHeader\fR, and \fBImage\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBFitsSlice\fR (const string FileName, const int SliceYSize, const int Overlap)"
.br
.RI "\fIconstructor. Overlap is the number of rows in common to successive slices (usually 0).\fR"
.ti -1c
.RI "int \fBLoadNextSlice\fR ()"
.br
.RI "\fIload next slice into memory.\fR"
.ti -1c
.RI "int \fBSliceSize\fR () const"
.br
.RI "\fIthe current slice size (differs from the constructor value at last slice).\fR"
.ti -1c
.RI "int \fBImageJ\fR (const int j) const"
.br
.RI "\fIthe coordinate in the full image of row j in present slice.\fR"
.ti -1c
.RI "bool \fBLastSlice\fR () const"
.br
.RI "\fIare we in the last slice?\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Memory saving traversal of a fits image.
.PP
This class is intended to access an image in a fits file, but only a slice of the image will reside in memory at a time. To be used when many images have to be accessed at the same time, in parallel (see \fBFitsParallelSlices\fR), or maybe to traverse a very big image. 
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for toads from the source code.