.TH "fitsslice.h" 3 "8 Feb 2004" "toads" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fitsslice.h \- Load successively slices of fits images in memory. 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fR
.br
\fC#include "fitsimage.h"\fR
.br
\fC#include <vector>\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBFitsParallelSlices\fR"
.br
.RI "\fISeveral fits images of the same size to be processed in parallel.\fR"
.ti -1c
.RI "class \fBFitsSlice\fR"
.br
.RI "\fIMemory saving traversal of a fits image.\fR"
.in -1c
.SS Typedefs

.in +1c
.ti -1c
.RI "typedef vector<\fBFitsSlice\fR*>::iterator \fBFitsSliceIterator\fR"
.br
.ti -1c
.RI "typedef vector<\fBFitsSlice\fR*>::const_iterator \fBFitsSliceCIterator\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Load successively slices of fits images in memory.
.PP
 When one needs image data for a single traversal, FitsSlices and \fBFitsParallelSlices\fR should be considered. At the moment both classes only provide input services. See  for an example.
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for toads from the source code.