.TH "fitsset.h" 3 "8 Feb 2004" "toads" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fitsset.h \- sets of fits files with homogeneous sizes, filter, and chip id. 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fR
.br
\fC#include <vector>\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBFitsSet\fR"
.br
.RI "\fIcontainer for fits files that have same sizes, filter, and come from the same chip within a mosaic.\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 
sets of fits files with homogeneous sizes, filter, and chip id.
.PP
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for toads from the source code.