.TH "GtransfoLinScale" 3 "8 Feb 2004" "toads" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GtransfoLinScale \- just here to provide specialized constructors. \fBGtransfoLin\fR fit routine. 
.SH SYNOPSIS
.br
.PP
\fC#include <gtransfo.h>\fR
.PP
Inherits \fBGtransfoLin\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBGtransfoLinScale\fR (const double Scale)"
.br
.ti -1c
.RI "\fBGtransfoLinScale\fR (const double ScaleX, const double ScaleY)"
.br
.ti -1c
.RI "int \fBNpar\fR () const"
.br
.RI "\fIreturns the number of parameters (to compute chi2's).\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 
just here to provide specialized constructors. \fBGtransfoLin\fR fit routine.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for toads from the source code.