.TH "GtransfoLinRot" 3 "8 Feb 2004" "toads" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GtransfoLinRot \- just here to provide a specialized constructor, and fit. 
.SH SYNOPSIS
.br
.PP
\fC#include <gtransfo.h>\fR
.PP
Inherits \fBGtransfoLin\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBGtransfoLinRot\fR ()"
.br
.ti -1c
.RI "\fBGtransfoLinRot\fR (const double AngleRad, const \fBPoint\fR *Center=NULL, const double ScaleFactor=1.0)"
.br
.ti -1c
.RI "double \fBfit\fR (const StarMatchList &List, const \fBGtransfo\fR *PriorTransfo=NULL, const \fBGtransfo\fR *PosteriorTransfo=NULL)"
.br
.RI "\fIfits a transfo to a list of star pairs (p1,p2).\fR"
.ti -1c
.RI "int \fBNpar\fR () const"
.br
.RI "\fIreturns the number of parameters (to compute chi2's).\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 
just here to provide a specialized constructor, and fit.
.PP
.SH MEMBER FUNCTION DOCUMENTATION
.PP 
.SS double GtransfoLinRot::fit (const StarMatchList & List, const \fBGtransfo\fR * PriorTransfo = NULL, const \fBGtransfo\fR * PosteriorTransfo = NULL)\fC [virtual]\fR
.PP
fits a transfo to a list of star pairs (p1,p2).
.PP
After the fit this(PriorTransfo(p1)) yields approximately PosteriorTransfo(p2). The returned value is the chi2. 
.PP
Reimplemented from \fBGtransfoLin\fR.

.SH AUTHOR
.PP 
Generated automatically by Doxygen for toads from the source code.