.TH "imageback.h" 3 "8 Feb 2004" "toads" \" -*- nroff -*-
.ad l
.nh
.SH NAME
imageback.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fR
.br
\fC#include "image.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBImageBack\fR"
.br
.RI "\fI\fBImage\fR Back class to compute an image of the background.\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 
 This class deals with the computation of background average and fluctuations. The computation is carried out by the constructor, using an algorithm borrowed from Sextractor (http://terapix.iap.fr/sextractor) : the average and sigma of pixels are computed over rectangles of size MeshStepX*MeshStepY, once using all pixels, and a second time using only pixels within 2 sigmas of the average. Then a median filter (of half width 1) is applied to both maps.
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for toads from the source code.