.TH "image.h" 3 "8 Feb 2004" "toads" \" -*- nroff -*-
.ad l
.nh
.SH NAME
image.h \- basic utilities for image algebra. 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fR
.br
\fC#include <algorithm>\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBImage\fR"
.br
.RI "\fIClass for the basic manipulation of images.\fR"
.ti -1c
.RI "class \fBImageWindow\fR"
.br
.ti -1c
.RI "class \fBPixelIterator\fR"
.br
.in -1c
.SS Defines

.in +1c
.ti -1c
.RI "#define \fBBADPIX\fR  -999"
.br
.ti -1c
.RI "#define \fBBIGVALUE\fR  1e+30"
.br
.in -1c
.SS Typedefs

.in +1c
.ti -1c
.RI "typedef float \fBPixel\fR"
.br
.in -1c
.SS Functions

.in +1c
.ti -1c
.RI "double \fBEmpiricCov\fR (const \fBImage\fR &Im1, const \fBImage\fR &Im2)"
.br
.RI "\fIReturns the empirical covariance of 2 images.\fR"
.ti -1c
.RI "double \fBImageAndWeightError\fR (const \fBImage\fR &I, const \fBImage\fR &W, const double MinWeight=0, double *AverageShift=NULL)"
.br
.RI "\fIreturn a clipped average of I*sqrt(W).\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 
basic utilities for image algebra.
.PP
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for toads from the source code.