.TH "lightcurvebuilder.h" 3 "8 Feb 2004" "toads" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lightcurvebuilder.h \- This class produces lightcurves of many objects, given images. 
.SH SYNOPSIS
.br
.PP
\fC#include "lightcurve.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBLightCurveBuilder\fR"
.br
.RI "\fILightcurve builder for one band. Execute different types of photometry.\fR"
.in -1c
.SS Typedefs

.in +1c
.ti -1c
.RI "typedef vector<\fBLightCurve\fR>::iterator \fBLightCurveIterator\fR"
.br
.ti -1c
.RI "typedef vector<\fBLightCurve\fR>::const_iterator \fBLightCurveCIterator\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
This class produces lightcurves of many objects, given images.
.PP
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for toads from the source code.