.TH "lightcurveguru.h" 3 "8 Feb 2004" "toads" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lightcurveguru.h \- A master class to run lightcurve builder in many bands. 
.SH SYNOPSIS
.br
.PP
\fC#include "reducedimage.h"\fR
.br
\fC#include "lightcurvebuilder.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBLightCurveGuru\fR"
.br
.RI "\fIMain lightcurve builder for all bands.\fR"
.ti -1c
.RI "struct \fBLightCurveParams\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
A master class to run lightcurve builder in many bands.
.PP
 
.PP
 The \fBLightCurveGuru\fR is ordering the processes to build the lightcurves from a set of images and points.
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for toads from the source code.