.TH "lightcurve.h" 3 "8 Feb 2004" "toads" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lightcurve.h \- A vector of FiducialStar of different nights The nights are usually geometrically aligned to use some of the routines of this class. 
.SH SYNOPSIS
.br
.PP
\fC#include "photstar.h"\fR
.br
\fC#include "night.h"\fR
.br
\fC#include "nightelement.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBLightCurve\fR"
.br
.RI "\fIThe same FiducialStar monitored many nights.\fR"
.in -1c
.SS Typedefs

.in +1c
.ti -1c
.RI "typedef \fBNightElement\fR<PhotStar> \fBFiducialStar\fR"
.br
.ti -1c
.RI "typedef ImageList<FiducialStar>::const_iterator \fBFiducialStarCIterator\fR"
.br
.ti -1c
.RI "typedef ImageList<FiducialStar>::iterator \fBFiducialStarIterator\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
A vector of FiducialStar of different nights The nights are usually geometrically aligned to use some of the routines of this class.
.PP
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for toads from the source code.