.TH "NamedValue" 3 "8 Feb 2004" "toads" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NamedValue \- very simple stuff to associate names and values. Used to I/O transfos to fits headers. 
.SH SYNOPSIS
.br
.PP
\fC#include <gtransfo.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBNamedValue\fR (const string &a_name, const double a_value)"
.br
.in -1c
.SS Public Attributes

.in +1c
.ti -1c
.RI "string \fBname\fR"
.br
.ti -1c
.RI "double \fBvalue\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
very simple stuff to associate names and values. Used to I/O transfos to fits headers.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for toads from the source code.