.TH "NewSub" 3 "8 Feb 2004" "toads" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewSub \- Handling of an actual subtraction (shift-coadd-subtract-detect). See  for the way to drive it. 
.SH SYNOPSIS
.br
.PP
\fC#include <newsub.h>\fR
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBNewSub\fR (const string &SubFileName, const bool Overwrite=false, const bool OnlyDet=false)"
.br
.RI "\fIthe constructor. see  for the syntax of the "subfile".\fR"
.ti -1c
.RI "\fB~NewSub\fR ()"
.br
.ti -1c
.RI "int \fBDoIt\fR ()"
.br
.ti -1c
.RI "void \fBFindGeometricReference\fR ()"
.br
.ti -1c
.RI "int \fBDoOneSub\fR (const \fBReducedImage\fR *RefStack, const \fBImageSum\fR *NewStack, const string &SubName, \fBImageSubtraction\fR *&\fBSub\fR)"
.br
.ti -1c
.RI "void \fBMatchDetectionsWithFakes\fR (\fBSEStarList\fR *Detections, const string &MatchListName)"
.br
.ti -1c
.RI "void \fBApplyCutsAndWrite\fR (\fBImageSubtraction\fR &ASubtraction)"
.br
.ti -1c
.RI "void \fBConstruction\fR (\fBImageSubtraction\fR &ASub, YquemStarList &stlcand)"
.br
.ti -1c
.RI "void \fBConstructMatchAndCut\fR ()"
.br
.ti -1c
.RI "void \fBCut_Write\fR (YquemStarList &stlcand, string &cutscanname)"
.br
.ti -1c
.RI "void \fBCut_Write\fR (CandStarList &stlcand)"
.br
.in -1c
.SS Public Attributes

.in +1c
.ti -1c
.RI "\fBImageSubtraction\fR* \fBSub\fR"
.br
.ti -1c
.RI "ImageSubtractionList \fBListOfSub\fR"
.br
.ti -1c
.RI "int \fBNumberOfSub\fR"
.br
.ti -1c
.RI "ReducedImageList \fBRef\fR"
.br
.ti -1c
.RI "ReducedNewList \fBListNewList\fR"
.br
.ti -1c
.RI "ReducedImageList \fBAllNew\fR"
.br
.ti -1c
.RI "ReducedImageList \fBAllImages\fR"
.br
.ti -1c
.RI "bool \fBoverwrite\fR"
.br
.ti -1c
.RI "bool \fBonlyDet\fR"
.br
.ti -1c
.RI "bool \fBonlyOneSub\fR"
.br
.ti -1c
.RI "SENearStarList* \fBFakeList\fR"
.br
.ti -1c
.RI "bool \fBAddFakes\fR"
.br
.ti -1c
.RI "bool \fBAssociateGal\fR"
.br
.ti -1c
.RI "bool \fBFixRef\fR"
.br
.ti -1c
.RI "const \fBReducedImage\fR* \fBGeometricReference\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Handling of an actual subtraction (shift-coadd-subtract-detect). See  for the way to drive it.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for toads from the source code.