.TH "NightSet" 3 "8 Feb 2004" "toads" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NightSet \- a class representing a set of overlapping images of the same night, same instrument and same filter. 
.SH SYNOPSIS
.br
.PP
\fC#include <reducedutils.h>\fR
.PP
Inherits ReducedImageList.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBNightSet\fR (const \fBReducedImage\fR &anImage)"
.br
.ti -1c
.RI "\fBNightSet\fR (const NightSet &Other)"
.br
.ti -1c
.RI "\fB~NightSet\fR ()"
.br
.ti -1c
.RI "bool \fBIsFromSameSet\fR (const \fBReducedImage\fR &Another) const"
.br
.RI "\fItrue if belongs to the same set.\fR"
.ti -1c
.RI "string \fBGenericName\fR () const"
.br
.RI "\fIreturns the generic string name of the set.\fR"
.ti -1c
.RI "void \fBdump\fR (ostream &Stream=cout) const"
.br
.ti -1c
.RI "double \fBSeeing\fR () const"
.br
.ti -1c
.RI "double \fBExposure\fR () const"
.br
.ti -1c
.RI "double \fBSignalToNoise23\fR () const"
.br
.in -1c
.SS Friends

.in +1c
.ti -1c
.RI "ostream& \fBoperator<<\fR (ostream &Stream, const NightSet &MySet)"
.br
.RI "\fIallows cout << NighSet;.\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 
a class representing a set of overlapping images of the same night, same instrument and same filter.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for toads from the source code.