.TH "Point" 3 "8 Feb 2004" "toads" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Point \- A point in a plane. 
.SH SYNOPSIS
.br
.PP
\fC#include <point.h>\fR
.PP
Inherited by \fBBaseStar\fR.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBPoint\fR (const double &xx=0, const double &yy=0)"
.br
.RI "\fI.TP
contructor.\fR"
.ti -1c
.RI "double \fBDistance\fR (const Point &Other) const"
.br
.RI "\fI-.\fR"
.ti -1c
.RI "double \fBDist2\fR (const Point &Other) const"
.br
.RI "\fIdistance squared to Other.\fR"
.ti -1c
.RI "template<class Operator> void \fBApply\fR (const Operator &Op)"
.br
.RI "\fIOperator can be e.g. a \fBGtransfo\fR.\fR"
.ti -1c
.RI "Point \fBoperator+\fR (const Point &Right) const"
.br
.RI "\fISum.\fR"
.ti -1c
.RI "Point \fBoperator-\fR (const Point &Right) const"
.br
.RI "\fIDifference.\fR"
.ti -1c
.RI "virtual void \fBdump\fR (ostream &s=cout) const"
.br
.in -1c
.SS Public Attributes

.in +1c
.ti -1c
.RI "double \fBx\fR"
.br
.RI "\fIcoordinate.\fR"
.ti -1c
.RI "double \fBy\fR"
.br
.RI "\fIcoordinate.\fR"
.in -1c
.SS Friends

.in +1c
.ti -1c
.RI "ostream& \fBoperator<<\fR (ostream &stream, const Point &point)"
.br
.RI "\fI-.\fR"
.in -1c
.SH DETAILED DESCRIPTION
.PP 
A point in a plane.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for toads from the source code.