.TH "point.h" 3 "8 Feb 2004" "toads" \" -*- nroff -*-
.ad l
.nh
.SH NAME
point.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fR
.br
\fC#include <cmath>\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBPoint\fR"
.br
.RI "\fIA point in a plane.\fR"
.in -1c
.SS Functions

.in +1c
.ti -1c
.RI "ostream& \fBoperator<<\fR (ostream &stream, const \fBPoint\fR &point)"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for toads from the source code.