.TH "simultaneousfit.h" 3 "8 Feb 2004" "toads" \" -*- nroff -*-
.ad l
.nh
.SH NAME
simultaneousfit.h \- A class to fit pixels simultaneously from a set of vignets. 
.SH SYNOPSIS
.br
.PP
\fC#include "imagelist.h"\fR
.br
\fC#include <lafnames.h>\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBSimultaneousFit\fR"
.br
.RI "\fISimultaneous fitting of Vignets.\fR"
.in -1c
.SS Typedefs

.in +1c
.ti -1c
.RI "typedef ImageList<VignetFit>::iterator \fBVignetFitIterator\fR"
.br
.ti -1c
.RI "typedef ImageList<VignetFit>::const_iterator \fBVignetFitCIterator\fR"
.br
.in -1c
.SS Enumerations

.in +1c
.ti -1c
.RI "enum \fBMinimMethod\fR { \fBLevenbergMarquardt\fR, \fBNewtonRaphson\fR }"
.br
.in -1c
.SS Variables

.in +1c
.ti -1c
.RI "const int \fBFitFlux\fR = 1"
.br
.ti -1c
.RI "const int \fBFitPos\fR = 2"
.br
.ti -1c
.RI "const int \fBFitGal\fR = 4"
.br
.ti -1c
.RI "const int \fBFitSky\fR = 8"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
A class to fit pixels simultaneously from a set of vignets.
.PP
.PP
 The model on a given vignet to be fitted is  Model(i,j) = flux*PSF(i-xc,j-yc) + [Gal X \fBKernel\fR](i,j) + sky where user chooses what to fit (flux, position, galaxy pixels and constant sky).  The flux and sky are free to change on each vignets, but the galaxy pixels  and the point source position are fixed at the best seeing resolution and photometric ratio vignet. PSF and \fBKernel\fR should be given and will not be fitted.
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for toads from the source code.