.TH "StampList" 3 "8 Feb 2004" "toads" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StampList \- Nothing but a list of Stamps. 
.SH SYNOPSIS
.br
.PP
\fC#include <dimage.h>\fR
.PP
Inherits list.
.PP
.SS Public Methods

.in +1c
.ti -1c
.RI "\fBStampList\fR (const \fBImage\fR &image, const BaseStarList &starList, const int hStampSize, const int MaxStamps)"
.br
.ti -1c
.RI "virtual \fB~StampList\fR ()"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
Nothing but a list of Stamps.
.PP


.SH AUTHOR
.PP 
Generated automatically by Doxygen for toads from the source code.