.TH "vignet.h" 3 "8 Feb 2004" "toads" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vignet.h \- A resizeable sub-image, with centered coordinates. 
.SH SYNOPSIS
.br
.PP
\fC#include "dimage.h"\fR
.br
\fC#include "countedref.h"\fR
.br
\fC#include "imagelist.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBVignet\fR"
.br
.RI "\fISimilar to \fBKernel\fR, but resizeable and contains some kind of \fBPoint\fR.\fR"
.in -1c
.SS Typedefs

.in +1c
.ti -1c
.RI "typedef ImageList<\fBVignet\fR> \fBVignetList\fR"
.br
.ti -1c
.RI "typedef VignetList::iterator \fBVignetIterator\fR"
.br
.ti -1c
.RI "typedef VignetList::const_iterator \fBVignetCIterator\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
A resizeable sub-image, with centered coordinates.
.PP
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for toads from the source code.