.TH "vignetfit.h" 3 "8 Feb 2004" "toads" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vignetfit.h \- a sub-image with its associated tabulated kernels, psfs, ... Mainly to use for \fBSimultaneousFit\fR. 
.SH SYNOPSIS
.br
.PP
\fC#include "vignet.h"\fR
.br
.SS Compounds

.in +1c
.ti -1c
.RI "class \fBVignetFit\fR"
.br
.in -1c
.SH DETAILED DESCRIPTION
.PP 
a sub-image with its associated tabulated kernels, psfs, ... Mainly to use for \fBSimultaneousFit\fR.
.PP
.PP
.SH AUTHOR
.PP 
Generated automatically by Doxygen for toads from the source code.