#!/usr/bin/env python

import os

Import('g_env')
local_env = g_env.Copy()


EXTRA_DIST = [
    'SConscript', 'Makefile.am'
    ]

SOURCE_FILES = [
    'dcopy.f',  'dger.f',    'dposv.f',   'dpotrs.f',  'dsyrk.f',   'dsytrs.f',  'dtrti2.f',  'ilaenv.f',
    'ddot.f',   'dlasyf.f',  'dpotf2.f',  'dscal.f',   'dsysv.f',   'dtrmm.f',   'dtrtri.f',  'lsame.f',
    'dgemm.f',  'dlauu2.f',  'dpotrf.f',  'dswap.f',   'dsytf2.f',  'dtrmv.f',   'idamax.f',  'xerbla.f',
    'dgemv.f',  'dlauum.f',  'dpotri.f',  'dsyr.f',    'dsytrf.f',  'dtrsm.f',   'ieeeck.f'
    ]


shlib = local_env.SharedLibrary(target='lapackstuff', source=SOURCE_FILES)

g_env.InstallLibs([shlib])
g_env.AddToDist(EXTRA_DIST + SOURCE_FILES)



# install targets
#Import('libDir')
#if libDir != '.':
#    lib_inst = local_env.Install(libDir, shlib)
#    local_env.AddPostAction(lib_inst, Chmod('$TARGETS', 0755))
#    local_env.Clean('uninstall', lib_inst)

#SOURCE_FILES = Glob(includes=['*.f'],
#                    excludes = None,
#                    dir='.')
