# -*- mode: python -*-
# 



def build( bld ):
    
    sources = bld.path.ant_glob('*.f')
        
    lib = bld(features = 'fc fcshlib', 
              source = sources,
              target = 'lapack_stuff', 
              #               libs   = ['gfortran'],
              #               libs   = ['g2c'],
              vnum     = '0.1.0' )
    
