# -*- mode: python -*-
# 

import frogsutils

def build( bld ):
    
    sources = bld.path.ant_glob('*.f')
        
    lib = bld(features = 'fc fcshlib', 
              source = sources,
              target = 'lapack_stuff', 
              #               libs   = ['gfortran'],
              #               libs   = ['g2c'],
              vnum     = frogsutils.get_version_number())
    
