#!/usr/bin/env python

import os

Import('g_env')
local_env = g_env.Copy()

EXTRA_DIST = [
    'SConscript', 'Makefile.am'
    ]

HEADER_FILES = [
    'addlcfakes.h',      'agaussian.h',
    'simsnstar.h',       'mcimage.h',
    'mcsub.h',           'simulation.h',
    'myrdm.h'
    ]

SOURCE_FILES = [
    'addlcfakes.cc',  'mcimage.cc',  'myrdm.cc',      
    'agaussian.cc',   'mcsub.cc',    'simsnstar.cc',
    'simulation.cc'
    ]

local_env.AddInternalDep('.')
local_env.AddInternalDep('objio',     'toadsio')
local_env.AddInternalDep('src',       'toads')
local_env.AddInternalDep('src_base',  'toadsbase')
local_env.AddInternalDep('src_utils', 'toadsutils')
local_env.AddInternalDep('dao',       'toadsdao')
local_env.ParseConfig('xml2-config --cflags')
local_env.ParseConfig('xml2-config --libs')


#local_env.AddExternalDep(['/home/nrl/software/cfitsio/v2r440/src'],
#                         ['/home/nrl/software/cfitsio/v2r440/Linux-i686'],
#                         ['cfitsio'])
#local_env.AddExternalDep(None,
#                         ['/usr/local/cern/pro/lib'],
#                         ['packlib', 'nsl', 'crypt', 'dl', 'g2c'])

shlib = local_env.SharedLibrary(target='toadsmc', source=SOURCE_FILES)

local_env.InstallLibs([shlib])
local_env.InstallHeaders(HEADER_FILES)

g_env.AddToDist(EXTRA_DIST + HEADER_FILES + SOURCE_FILES)

