#!/usr/bin/env python

import os
#from config import Glob

Import('g_env')
local_env = g_env.Copy()


EXTRA_DIST = ['Makefile.am', 'SConscript',
              'alltelinst.cc', 'virtualinstrument.cc', 'slasub.c']

HEADER_FILES = [
    'alltelinst.h',  'fitsimage.h',  'image.h',       
    'astroutils.h',  'fitstoad.h',   'point.h',       'vutils.h',
    'fileutils.h',   'frame.h',      'stringlist.h',
    ]

NOINST_HEADER_FILES = [
    'virtualinstrument.h',  'wcs_defines.h',   'wcscon.h'
    ]

SOURCE_FILES = [
    'image.cc',     'fitsimage.cc',
    'vutils.cc',    'frame.cc',
    'fileutils.cc', 'stringlist.cc',
    'fitstoad.cc',  'astroutils.cc',
    'wcscon.c'
    ]

local_env.AddInternalDep('.')
local_env.ActivateExternalPackage('cfitsio')
#local_env.AddExternalDep('/home/nrl/software/cfitsio/v2r440/src',
#                         ['/home/nrl/software/cfitsio/v2r440/Linux-i686'],
#                         ['cfitsio'])

#local_env.ExternalPackage(cern)
shlib = local_env.SharedLibrary(target='toadsbase', source=SOURCE_FILES)

g_env.InstallLibs([shlib])
g_env.InstallHeaders(HEADER_FILES)
g_env.AddToDist(EXTRA_DIST + SOURCE_FILES + HEADER_FILES + NOINST_HEADER_FILES)


