// -*- C++ -*-
// 
// file test_dict_rw.cc
// simple test program, to test the parsing 
// of the files generated by SWIG
// 
#include <unistd.h>

#include <iostream>
#include <string>

#include "dict.h"
#include "swig_dict_reader.h"
#include "xmlschema_dict_writer.h"


void usage()
{
  std::cerr << "usage: test_dict_rw [OPTIONS] <input_file>" << std::endl;
  std::cerr << "       OPTIONS:                           " << std::endl;
  std::cerr << "        -x <outfile>  xml dict            " << std::endl;
  std::cerr << "        -X <outfile>  XML Schema dict     " << std::endl;
  exit(-1);
}

int
main(int argc, char** argv)
{
  int output_type=0; // default xml file
  std::string ofname="tdrw.xml";
  std::string filename;
  
  char c;
  while( (c=getopt(argc, argv, "x:X:")) != -1 ) 
    switch(c) {
    case 'x':
      ofname = optarg;
      break;
    case 'X':
      output_type=1;
      ofname=optarg;
      break;
    default:
      usage();
    }
  if(optind>=argc) usage();
  filename=argv[optind];
  
  swig_dict_reader rd(filename.c_str());
  std::cout << " rd.size()=" << rd.size() << std::endl;
  
  
  xmlschema_dict_writer w("glop.xsd");  
  dict d;
  rd.read(d); w.write(d);
  rd.read(d); w.write(d);
  rd.read(d); w.write(d);
  rd.read(d); w.write(d);
  rd.read(d); w.write(d);
  rd.read(d); w.write(d);
}
