#ifndef LIGHTCURVEFILE__H
#define LIGHTCURVEFILE__H


#include "objecttofit.h"
#include "reducedimage.h"


#include <list>
#include <string>
#include "pmstar.h"
#include "rimage.h"


class LightCurveFile
{
 private:
  ObjectToFitList objects;
  RImageList images;
  RImageRef geomRef;
  bool writeVignettes;
  bool writeMatrices; 
  bool subDirPerObject;
  bool useProperMotions;
  PmStarList pmStarList;
  std::string pmStarListFileName;

 public:
  
  LightCurveFile(const string &LCFileName);

  //! regular fit: fits objects in LCFile
  bool SimPhotFitAll(double vignette_size_n_seeing=-1) const;

  //! fit objects in calib catalog
  bool  SimPhotFitAllCalib(const string &CalibCatalog, const string &OutputCatalog, 
			   int itype=1, int Nmax=-1, double vignette_size_n_seeing=-1) const;

  RImageRef GeomRef() const { return geomRef;}
  const RImageList &Images() const { return images;}

  bool WriteVignettes() const { return writeVignettes;}
  bool WriteMatrices()  const { return writeMatrices;}
  void PleaseWriteVignettes() { writeVignettes = true;}
  void PleaseWriteMatrices() { writeMatrices = true;}

  bool OneDirPerObject() const { return subDirPerObject;}
  void PleaseOneDirPerObject() { subDirPerObject = true;}

  const std::string &PmStarListFileName() const {return pmStarListFileName;}

  const PmStar* FindNearestPmStar(const Point &Where) const;
  double RefMJD() const { return pmStarList.refDate;}

  bool UseStoredTransfos() const 
  { return useProperMotions; /* since both proper motions and transfos are computed by pmfit */}

};


/*!
 \page lightfile2 Syntax of the "lightfile"
 
 A light curve file consists of objects and images.
 Comment are coded with the '#' at the beginning of the line.
 The expected format is the following:
 
 \code
 
 # X Y [DATE_MIN=MJD_MIN DATE_MAX=MJD_MAX NAME=toto BAND=xyz]
 # X Y : starting coordinates of the supernova
 # Sn flux will be fitted on images within [date_min, date_max], and forced to zero outside. 
 # NAME and BAND are used to name files on output. 
 # TYPE tells what is to be fitted :
 #      -1 : flux galaxy 
 #       0 : flux galaxy pos (default)
 #       1 : flux pos
 #       2 : galaxy
 #       3 : flux

 OBJECTS
 510.20 1043.98 DATE_MIN=54xxx DATE_MAX=54yyy TYPE=<int> NAME=R4D14-4
 
 # The list of all DbImages in a single filter
 IMAGES
 DbImage1
 DbImage2
 DbImage3
 DbImage4
   .
   .
   .
 # photometric reference. It should be the best seeing image 
 PHOREF
 PhoRefDbImage

 # calalog of stars including proper motions (generated by pmfit from the same input file)
 PMLIST 
 PmListName
 \endcode
*/ 





#endif /* LIGHTCURVEFILE__H */
