#!/usr/bin/env python

import os

Import('g_env')
local_env = g_env.Copy()

EXTRA_DIST = [
    'SConscript', 'Makefile.am'
    ]

PROGRAM_FILES =  [
    'header.cc',              'astrom.cc',                     'changekey.cc',
    'checker.cc',             'create_precise_std_file.cc',    'dbimstat.cc',
    'dead_correction.cc',     'elixir_to_toads.cc',            'findsatellite.cc',
    'image_align.cc',         'image_register.cc',             'image_select.cc',
    'image_stats.cc',         'image_sub.cc',                  'image_sum.cc',
    'lbl2toads.cc',           'maglimeval.cc',                 'make_catalog.cc',
    'make_cosmic.cc',         'make_phot.cc',                  'make_dead.cc', 
    'joinlist.cc',            'makesub.cc',                    'make_weight.cc',
    'matchstandard.cc',       'matchusno.cc',                  'preptoads.cc',
    'removeback.cc',          'selection.cc',                  'skylev.cc',
    'sum_images.cc',          'valid_fits.cc',                 'make_daophot.cc',
    'make_lightcurve.cc',     'rustine_for_fringe.cc',         'assign.cc',
    'dbls.cc',                'split_fits.cc',                 'testdao.cc',
    'fitnight.cc',            'invertdeadmap.cc',              'install_image.cc',
    'vignet4gif.cc',          'modelvignet.cc',                'wrapswarp.cc',
    'compute.cc',             'enlargeimage.cc',               'calibrate.cc',
    'coordfromimage.cc',      'enlargedead.cc',                'mask2dead.cc',
    'mkcat2.cc',              'seeing.cc',                     'mergelists.cc',
    'genlcfakes.cc',          'modelpsf.cc',                   'zpfitter.cc',
    'calibrationhacker.cc',   'basicaperture.cc',              'calibratefixedpos.cc',
    'flatfield.cc']



local_env.AddInternalDep('objio',        'toadsio')
local_env.AddInternalDep('src_base',     'toadsbase')
local_env.AddInternalDep('src',          'toads')
local_env.AddInternalDep('src_utils',    'toadsutils')
local_env.AddInternalDep('flat',         'toadsflat')
local_env.AddInternalDep('lapack_stuff', 'lapackstuff')
local_env.AddInternalDep('cern_stuff',   'cern_stuff')
local_env.AddInternalDep('dao',          'toadsdao')
local_env.AddInternalDep('mc',           'toadsmc')
local_env.AddInternalDep('lc',           'toadslc')
local_env.ActivateExternalPackage('cern')


# ugly hack, so that we can find the __persister.h files...
local_env.AddInternalDep('%s/src' % (local_env['builddir']))
local_env.AddInternalDep('%s/lc' % (local_env['builddir']))

local_env.ParseConfig('xml2-config --cflags')
local_env.ParseConfig('xml2-config --libs')

#local_env.AddExternalDep(['/home/nrl/software/sex/v222/src/'],
#                         ['/home/nrl/software/sex/v222/Linux-i686'],
#                         ['sex', 'wcs'])
#local_env.AddExternalDep(['/home/nrl/software/cfitsio/v2r440/src'],
#                         ['/home/nrl/software/cfitsio/v2r440/Linux-i686'],
#                         ['cfitsio'])
#local_env.AddExternalDep(None,
#                         ['/usr/local/cern/pro/lib'],
#                         ['packlib', 'nsl', 'crypt', 'dl', 'g2c'])

progs = []
for f in PROGRAM_FILES:
    progs.append(local_env.Program(source=f))

local_env.InstallProgs(progs)

g_env.AddToDist(EXTRA_DIST + PROGRAM_FILES)


