# -*- mode: python -*-
# 





def build( bld ):
    
    sources = """header.cc astrom.cc changekey.cc checker.cc dbimstat.cc
                 dead_correction.cc elixir_to_toads.cc
                 findsatellite.cc image_align.cc image_register.cc
                 image_select.cc image_stats.cc image_sub.cc image_sum.cc
                 lbl2toads.cc maglimeval.cc make_catalog.cc
                 make_cosmic.cc make_dead.cc joinlist.cc make_weight.cc
                 matchusno.cc preptoads.cc removeback.cc selection.cc
                 skylev.cc sum_images.cc valid_fits.cc make_lightcurve.cc
                 rustine_for_fringe.cc assign.cc dbls.cc split_fits.cc
                 fitnight.cc invertdeadmap.cc install_image.cc
                 vignet4gif.cc modelvignet.cc wrapswarp.cc compute.cc
                 enlargeimage.cc calibrate.cc coordfromimage.cc
                 enlargedead.cc mask2dead.cc mkcat2.cc seeing.cc
                 mergelists.cc modelpsf.cc zpfitter.cc
                 calibrationhacker.cc basicaperture.cc
                 calibratefixedpos.cc flatfield.cc makepsf.cc
                 compute_zp.cc splitsubs.cc test_dust.cc makvar.cc
                 getvalueatpoint.cc catalog_images_match.cc
                 deadprop.cc checkmask.cc sumpixels.cc wcs_for_vignets.cc
                 apercorr.cc simple_zpfitter.cc""".split()

    
    for src in sources:
        
        target = src.replace('.cc', '')
        
        bld( features = 'cxx cprogram', 
             source = src,
             target = target,
             includes = [ '.', '../src_utils', '../src_base', '../src', '../flat',
                          '../../sex/src', '../../cfitsio/src', 
                          '../psf', 
                          '../lc' ], 
             libs     = [ 'm', 'sex', 'wcs', 'fits', 'cfitsio', 'z'], 
             libpath  = [ '../../sex/build/default/src', 
                          '../../sex/build/default/src/wcs', 
                          '../../sex/build/default/src/fits', 
                          '../../cfitsio/src'], 
             uselib_local = [ 'toads_base', 
                              'toads_utils', 
                              'lapack_stuff', 
                              'cern_stuff', 
                              'toadsflat',
                              'toadslib', 
                              'toadspsf',
                              'toadslc' ], 
             vnum     = '0.1.0' )
                  



