# -*- mode: python -*-
# 



def build( bld ):
    
    for tg in ['l2tup','im2tup','2im2tup'] :
        prog = bld.program(
            source = tg+'.cc',
            target = tg,
            includes = [ '.', '../src_base' ],
            lib      = [ 'm', 'cfitsio', 'z'],
            uselib = 'CERN',
            use = ['toads_base', 'toads_utils'],
            vnum     = '0.1.0', 
            rpath = bld.env['PREFIX'] + '/lib')

