 /* Automatically generated by make from ../telinst/cfh12k.cc ../telinst/cfhtmos.cc ../telinst/ctio1p5.cc ../telinst/ctiobtc.cc ../telinst/ctiomos2.cc ../telinst/esodanish.cc ../telinst/hstacs.cc ../telinst/hstwfpc2.cc ../telinst/intwfc.cc ../telinst/jkt.cc ../telinst/keckIIesi.cc ../telinst/keckIlris.cc ../telinst/kpnot1ka.cc ../telinst/lick1m.cc ../telinst/megacam.cc ../telinst/not.cc ../telinst/nttsusi.cc ../telinst/swarp.cc ../telinst/tng.cc ../telinst/vltfors.cc ../telinst/vltisaac.cc ../telinst/whtwfc.cc ../telinst/wiyns2kb.cc ../telinst/yaloandicam.cc */
 /* makefile at the end of fitstoad.cc */
#ifndef ALLTELINST__H
#define ALLTELINST__H
class Cfht12K;
class Int4Wfc;
class IntWfcNewDaq;
class Megacam;
#endif
