#!/usr/bin/env python

import os
#from config import Glob

Import('g_env')
local_env = g_env.Copy()
local_env.Append(YACCFLAGS='-l -d')

EXTRA_DIST = [
    'Makefile.am', 'SConscript'
    ]

NOINST_HEADER_FILES = [
    'docmain.h'
    ]

HEADER_FILES = [
    'align_box.h',           'dynccd.h',               'nstarmatch.h',
    'allreducedimage.h',     'exceptions.h',           'psfmatch.h',
    'apersestar.h',          'fastfinder.h',           'quali_box.h',
    'fmath.h',               'reducedimage.h',         'basestar.h',
    'gaussianfit.h',         'reducedutils.h',         'globalval.h',            
    'gtransfocomposition.h', 'seeing_box.h',           'cfortran.h',
    'gtransfo.h',            'senearstar.h',           'cluster2.h',
    'histopeakfinder.h',     'sestar.h',               'cluster.h',
    'hprofile1d.h',          'sextractor_box.h',       'convolution.h',
    'imagebinning.h',        'simps2d.h',              'convtemplate.h',
    'imagelist.h',           'standardstar.h',         'nightelement.h',
    'countedref.h',          'imagematch.h',           'starlist.h',
    'datacards.h',           'imagesubtraction.h',     'starmatch.h',
    'datdetec.h',            'imagesum.h',             'sub.h',
    'imageutils.h',          'subimage.h',
    'dbimage.h',             'jimstar.h',              'swarpstack.h',
    'defs.h',                'kernelfit.h',            'toadscards.h',
    'detection.h',           'transformedimage.h',     'nbrandom.h',
    'dicstar.h',             'listmatch.h',            'usnoutils.h',
    'dictfile.h',            'nbconst.h',              'wcsutils.h',
    'dimage.h' #, 'kernelfit_dict.h'
    ]

SOURCE_FILES = [
    'kernelfit_dict.cc',   'reducedimage_dict.cc',
    'starlist.cc',         'dbfileParse.y',       'dbfileLex.l',
    'wcsutils.cc',         'toadscards.cc',       'datacards.cc',          
    'datdetec.cc',         'basestar.cc',         'jimstar.cc',            
    'nstarmatch.cc',       'sestar.cc',           'standardstar.cc',       
    'starmatch.cc',        'listmatch.cc',        'fastfinder.cc',         
    'usnoutils.cc',        'gtransfo.cc',         'align_box.cc',          
    'quali_box.cc',        'seeing_box.cc',       'sextractor_box.cc',     
    'reducedutils.cc',     'dimage.cc',           'detection.cc',
    'allreducedimage.cc',  'dbimage.cc',          'imagematch.cc',
    'imagesubtraction.cc', 'sub.cc',              'imagesum.cc',
    'reducedimage.cc',     'subimage.cc',         'transformedimage.cc',
    'cluster.cc',          'convolution.cc',      'kernelfit.cc',
    'psfmatch.cc',         'swarpstack.cc',	  'dicstar.cc',
    'histopeakfinder.cc',  'dictfile.cc',	  'apersestar.cc',
    'globalval.cc',        'hprofile1d.cc',       'imageutils.cc',
    'gaussianfit.cc'
    ]

local_env.CFile(target=['dbfileParse.h', 'dbfileParse.c'],
                source='dbfileParse.y')
local_env.CFile(target='dbfileLex', source='dbfileLex.l')
local_env.AddInternalDep('.')
local_env.AddInternalDep('objio',     'toadsio')
local_env.AddInternalDep('%s/src' % (local_env['builddir']))
local_env.ParseConfig('xml2-config --cflags')
local_env.ParseConfig('xml2-config --libs')
local_env.AddInternalDep('src_base',  'toadsbase')
local_env.AddInternalDep('src_utils', 'toadsutils')
local_env.ActivateExternalPackage('sex')
local_env.ActivateExternalPackage('cfitsio')

#local_env.Dictgen(['kernelfit', 'kernelfit_dict.h'])
#local_env.Dictgen(['reducedimage', 'reducedimage_dict.h'])

local_env.Dictgen('kernelfit')
local_env.Dictgen('reducedimage')

#local_env.AddExternalDep(['/home/nrl/software/sex/v222/src/'],
#                         ['/home/nrl/software/sex/v222/Linux-i686'],
#                         ['sex', 'wcs'])

shlib = local_env.SharedLibrary(target='toads', source=SOURCE_FILES)

local_env.InstallLibs([shlib])
local_env.InstallHeaders(HEADER_FILES)
g_env.AddToDist(EXTRA_DIST + SOURCE_FILES + HEADER_FILES + NOINST_HEADER_FILES)

