#!/usr/bin/env python

import os


Import('g_env')
local_env = g_env.Copy()

EXTRA_DIST = ['SConscript', 'Makefile.am']

HEADER_FILES = [
    'fringeutils.h',
    'fitsimagearray.h',
    'fitsset.h',
    'superflat.h'
    ]

LIB_SOURCE_FILES = [
    'fringeutils.cc',
    'fitsimagearray.cc',
    'fitsset.cc',
    'superflat.cc'
    ]

PROG_SOURCE_FILES = [
    'defringe.cc',   
    'fringefinder.cc',
    'medianstack.cc',
    'trim.cc',       
    'correlation.cc'
    ]

local_env.AddInternalDep('.')
local_env.AddInternalDep('objio',     'toadsio')
local_env.AddInternalDep('src',       'toads')
local_env.AddInternalDep('src_base',  'toadsbase')
local_env.AddInternalDep('src_utils', 'toadsutils')
local_env.AddInternalDep('lapack_stuff', 'lapackstuff')
local_env.AddInternalDep('cern_stuff', 'cern_stuff')

# local_env.ActivateExternalPackage('cern')
local_env.ActivateExternalPackage('cfitsio')
local_env.ParseConfig('xml2-config --libs')
local_env.ParseConfig('xml2-config --cflags')

shlib = local_env.SharedLibrary(target='toadsflat', source=LIB_SOURCE_FILES)

prog_local_env = local_env.Copy()
prog_local_env.AddInternalDep('flat', 'toadsflat')
prog_local_env.AddInternalDep('lapack_stuff', 'lapackstuff')

progs = []
progs.append(prog_local_env.Program('defringe', source='defringe.cc'))
progs.append(prog_local_env.Program('fringefinder', source='fringefinder.cc'))
progs.append(prog_local_env.Program('medianstack', source='medianstack.cc'))
progs.append(prog_local_env.Program('trim', source='trim.cc'))
progs.append(prog_local_env.Program('correlation', source='correlation.cc'))

g_env.InstallHeaders(HEADER_FILES)
g_env.InstallLibs([shlib])
g_env.InstallProgs(progs)
g_env.AddToDist(EXTRA_DIST + HEADER_FILES + LIB_SOURCE_FILES + PROG_SOURCE_FILES)

